In [18]:
import pandas as pd
import numpy as np

def mp_model(dot,t):
	if dot >= t: return 1
	else: return 0

w = np.array([1,-1])
input_data = np.array([[0,0],[0,1],[1,0],[1,1]])

dot_product = input_data @ w
t = 1

for i in range(0,4):
	Activation_f = mp_model(dot_product[i],t)
	print("Activation: ",Activation_f)

Activation:  0
Activation:  0
Activation:  1
Activation:  0


AND NOT

In [2]:
def mp_model(dot,t):
  if dot >= t:
    return 1
  else:
    return 0

In [3]:
w = np.array([1,-1])
w

array([ 1, -1])

In [4]:
input_data = np.array([[0,0],[0,1],[1,0],[1,1]])
input_data

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [5]:
dot_product = input_data @ w
t = 1


In [6]:
dot_product

array([ 0, -1,  1,  0])

In [7]:
for i in range(0,4):
  Activation_f = mp_model(dot_product[i],t)
  print("Activation: ",Activation_f)


Activation:  0
Activation:  0
Activation:  1
Activation:  0


In [8]:
# y_value = np.array([0,0,1,1])
# y_value

In [9]:
# w_pred = y_value @ input_data
# w_pred

AND GATE

In [10]:
and_w = np.array([1,1])
and_w

array([1, 1])

In [11]:
and_product = input_data @ and_w
and_product

array([0, 1, 1, 2])

In [12]:
t = 2

In [13]:
for i in range(0,4):
  And_Activation = mp_model(and_product[i],t)
  print("AND Activation: ",And_Activation)

AND Activation:  0
AND Activation:  0
AND Activation:  0
AND Activation:  1
